### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by shorelines100** [nypublicradio/audiogram#64] opened 2016-11-20 14:55 UTC
I finally got this working on a vagrant build. But I'm getting this error whenever I generate an audiogram, it shows up as 'unknown error' on the interface.

<img width="720" alt="screenshot 2016-11-20 22 53 01" src="https://cloud.githubusercontent.com/assets/16102653/20463709/2efb32ba-af74-11e6-8327-f699b7731045.png">

**Comment by veltman** [comment] 2016-11-22 16:10
I suspect this is an instance of: https://github.com/nypublicradio/audiogram/issues/63

Not sure why this is suddenly popping up for several people in the last few days (nothing has changed, that I know of) - but until I can patch it the fix would be to enable Redis as detailed in that thread.

**Comment by veltman** [comment] 2017-01-05 22:36
Closing as duplicate of #63

**Closed by veltman** 2017-01-05 22:36 UTC
