### ISSUE TITLE
manifest for ubuntu:16.04 not found

### ISSUE THREAD

**Issue by philoushka** [nypublicradio/audiogram#79] opened 2017-02-28 20:30 UTC
I'm running this on a Digital Ocean Docker VM. 
Ubuntu 16.04.

How can I work around this problem?

>docker build -t audiogram https://github.com/nypublicradio/audiogram.git

Sending build context to Docker daemon 557.1 kB
Sending build context to Docker daemon 6.128 MB
Sending build context to Docker daemon 11.14 MB
Sending build context to Docker daemon 13.27 MB

Step 1/10 : FROM ubuntu:16.04
manifest for ubuntu:16.04 not found

**Comment by veltman** [comment] 2017-03-13 18:55
Hmm, I'm not able to reproduce this.

My steps:

1. Start creating new droplet (via https://cloud.digitalocean.com/droplets/new)
2. Choose "One-click apps"
3. Select "Docker 17.03.0-ce on 16.04"
4. Click "Create" on the bottom of the page
5. SSH into the newly-created droplet (`ssh root@[ip address]`)
6. Run `docker build -t audiogram https://github.com/nypublicradio/audiogram.git`

This commence about a million automatic updates, but it seems to work, and certainly doesn't get hung up on Step 1 or throw a manifest error.

Are there any relevant differences between this and your setup? Did you install Docker manually? I'm not sure what would make it unable to pull that image off the registry in your case.

**Comment by veltman** [comment] 2017-03-16 20:51
Closing this as idle, feel free to re-open if you're still having this issue!

**Closed by veltman** 2017-03-16 20:51 UTC
